# This is a basic workflow to help you get started with Actions

name: Download 91
on:
  push:
    branches: [ "main" ]
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download
        uses: actions/checkout@v3
        env:
          SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }}
        with:
          host: ${{ secrets.SERVER_HOST }} #服务器地址
          username: ${{ secrets.SERVER_USERNAME }} #用户名
          key: ${{ secrets.SERVER_KEY }} #私钥 安全问题一定都以变量的方式传递！！！
          envs: SERVER_WORKDIR #使用工作目录变量
          # 进入到项目目录，执行依赖更新
          script: |
            cd $SERVER_WORKDIR #进入到工作目录
            docker exec -it spider bash update.sh
            
