# This is a basic workflow to help you get started with Actions

name: Download 91
on:
  push:
    branches: [ "main" ]
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker exec spider bash update.sh
            
