# This is a basic workflow to help you get started with Actions

name: Download 91
on:
  push:
    branches: [ "main" ]
    paths-ignore:  # 下列文件的变动不触发
      - 'bbb/b.txt'
      - README.md
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker exec spider bash /usr/src/myapp/shell/run_scripts_91.sh 1>/dev/null 2>&1 &
            
