# This is a basic workflow to help you get started with Actions

name: Download 91
on:
  push:
    branches: [ "main" ]
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download
        uses: actions/checkout@v3
        with:
          host: ${{ secrets.SERVER_HOST }} #服务器地址
          username: ${{ secrets.SERVER_USERNAME }} #用户名
          key: ${{ secrets.SERVER_KEY }} #私钥 安全问题一定都以变量的方式传递！！！
          script: |
            docker exec -it spider bash update.sh
            echo 'test' > /root/test.txt
            
